name: Build
on:
  push:
    branches:
      - main

jobs:
  check:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Lint
        uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run lint
